CREATE TABLE IF NOT EXISTS zinc_stock (
  id TINYINT NOT NULL PRIMARY KEY,
  initialized TINYINT(1) NOT NULL DEFAULT 0,
  plant_kg DECIMAL(14,3) NOT NULL DEFAULT 0,
  kettle_kg DECIMAL(14,3) NOT NULL DEFAULT 0,
  kg_per_mm DECIMAL(10,3) NULL,
  revision INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
