const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const fmt=value=>Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:3});
const money=value=>Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const clean=value=>String(value??'-').normalize('NFKD').replace(/[^\x20-\x7E]/g,'');

async function generateMonthlyReportPdf(report){
  const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  let page,y;const addPage=()=>{page=pdf.addPage([841.89,595.28]);y=558;page.drawText('IV SQUARE STRUCTURE INDIA PVT LTD',{x:34,y,size:14,font:bold,color:rgb(.15,.13,.25)});page.drawText(`MONTHLY OPERATIONS REPORT | ${clean(report.period.label)}`,{x:490,y,size:9,font:bold,color:rgb(.24,.18,.5)});y-=24;page.drawText(`Financial year ${clean(report.financial_year.name)} | ${report.period.from} to ${report.period.to}`,{x:34,y,size:8,font:regular,color:rgb(.4,.38,.48)});y-=24;};
  const heading=text=>{if(y<75)addPage();page.drawRectangle({x:34,y:y-16,width:774,height:22,color:rgb(.24,.18,.5)});page.drawText(clean(text),{x:43,y:y-9,size:9,font:bold,color:rgb(1,1,1)});y-=28;};
  const row=(label,value)=>{if(y<52)addPage();page.drawText(clean(label),{x:43,y,size:8,font:regular,color:rgb(.2,.19,.28)});page.drawText(clean(value),{x:470,y,size:8,font:bold,color:rgb(.15,.13,.25)});y-=18;};
  const table=(columns,rows)=>{if(y<90)addPage();const widths=columns.map(c=>c.width);let x=38;columns.forEach((c,i)=>{page.drawText(c.title,{x,y,size:7,font:bold});x+=widths[i];});y-=14;rows.forEach(item=>{if(y<45){addPage();x=38;columns.forEach((c,i)=>{page.drawText(c.title,{x,y,size:7,font:bold});x+=widths[i];});y-=14;}x=38;columns.forEach((c,i)=>{let value=clean(item[c.key]);while(regular.widthOfTextAtSize(value,7)>widths[i]-5&&value.length>3)value=value.slice(0,-1);page.drawText(value,{x,y,size:7,font:regular});x+=widths[i];});y-=15;});y-=7;};
  addPage();heading('PRODUCTION SUMMARY');row('Production entries',fmt(report.production.entry_count));row('Production days',fmt(report.production.production_days));row('Quantity',`${fmt(report.production.quantity)} NOS`);row('MS production',`${fmt(report.production.total_ms_kg)} kg`);row('GI production',`${fmt(report.production.total_gi_kg)} kg`);row('Zinc used after recovery',`${fmt(report.production.net_zinc_kg)} kg`);row('Zinc consumption after recovery',`${fmt(report.production.zinc_consumption_percent)}%`);
  heading('ZINC STOCK');row('Opening plant / kettle',`${fmt(report.zinc.opening_plant_kg)} / ${fmt(report.zinc.opening_kettle_kg)} kg`);row('Purchased zinc received',`${fmt(report.zinc.received_kg)} kg`);row('Added to kettle',`${fmt(report.zinc.transferred_to_kettle_kg)} kg`);row('Production use / restored',`${fmt(report.zinc.production_used_kg)} / ${fmt(report.zinc.production_restored_kg)} kg`);row('Closing plant / kettle',`${fmt(report.zinc.closing_plant_kg)} / ${fmt(report.zinc.closing_kettle_kg)} kg`);
  heading('ASH & DROSS');row('Ash collected',`${fmt(report.byproducts.ash_weight_kg)} kg`);row('Dross collected',`${fmt(report.byproducts.dross_weight_kg)} kg`);row('Recovered zinc',`${fmt(report.byproducts.recovered_zinc_kg)} kg`);row('Sale value with GST',`Rs ${money(report.byproducts.total_with_gst)}`);
  heading('EXPENSE & PLANT COST');row('Total expense',`Rs ${money(report.expenses.totals.total_expense)}`);row('Running plant cost',`Rs ${money(report.expenses.totals.running_plant_cost)} / kg`);
  heading('SHIFT PRODUCTION');table([{title:'Shift',key:'shift_name',width:100},{title:'Entries',key:'entry_count',width:80},{title:'Qty',key:'quantity',width:100},{title:'MS kg',key:'ms_kg',width:120},{title:'GI kg',key:'gi_kg',width:120}],report.shifts);
  heading('MATERIAL PRODUCTION');table([{title:'Material',key:'material',width:280},{title:'Qty',key:'quantity',width:90},{title:'MS kg',key:'ms_kg',width:110},{title:'GI kg',key:'gi_kg',width:110}],report.materials);
  heading('CONTRACTOR PRODUCTION');table([{title:'Contractor',key:'contractor_name',width:220},{title:'Entries',key:'entry_count',width:75},{title:'Qty',key:'quantity',width:90},{title:'MS kg',key:'ms_kg',width:110},{title:'GI kg',key:'gi_kg',width:110}],report.contractors);
  heading('PLANNING');table([{title:'Challan',key:'challan_no',width:120},{title:'Party',key:'party_name',width:155},{title:'Material',key:'material_description',width:230},{title:'Planned',key:'planned_qty',width:70},{title:'Produced',key:'produced_qty',width:70},{title:'Status',key:'status',width:80}],report.planning);
  heading('EXPENSE BREAKDOWN');Object.entries(report.expenses.expenses).forEach(([key,value])=>row(key.replaceAll('_',' '),`Rs ${money(value)}`));
  heading('ZINC MOVEMENTS');table([{title:'Date',key:'created_at',width:120},{title:'Type',key:'movement_type',width:110},{title:'Amount kg',key:'amount_kg',width:80},{title:'Plant after',key:'plant_after_kg',width:90},{title:'Kettle after',key:'kettle_after_kg',width:90},{title:'Note',key:'note',width:260}],report.zinc_movements);
  return Buffer.from(await pdf.save());
}
module.exports={generateMonthlyReportPdf};
